### PR TITLE
Fix #141: Simplify missing data error message

### LINKED ISSUE #141: Better error recovery
We've either broken Heroku/Transposer, or I'm in a magical mid-deployment dead zone.

firefox_public_data_report

Regardless of the details, we should have a better recovery than:

> **Error fetching dashboard**
> JSON.parse: unexpected character at line 1 column 1 of the JSON data

Where https://ensemble-transposer.herokuapp.com/user-activity is currently 404ing with the glorious message of:

> "Not found"

Which the front end is trying to parse as JSON, and failing.

### PR DESCRIPTION
**Pull request by openjck**
Do not display a message about JSON.parse() to the user, but do show it
in the console. Unfortunately, because of the way ensemble and
ensemble-transposer are hosted, it's not possible to determine if an
error results from a dataset not existing.

### CODE REVIEW

File: src/components/containers/DashboardContainer.js [hunk 1]
```diff
@@ -24,17 +24,15 @@ class DashboardContainer extends React.Component {
         if (dataFetch.pending) {
             return <Spinner />;
         } else if (dataFetch.rejected) {
-            const extraErrorComponentProps = {};
-
             if (dataFetch.reason && dataFetch.reason.message) {
-                extraErrorComponentProps.message = dataFetch.reason.message;
+                // eslint-disable-next-line no-console
+                console.error(dataFetch.reason.message);
```
Comment (spasovski) [inline src/components/containers/DashboardContainer.js]: Yea I am totally fine with these even though the community has taken a dislike to console logs. If this was an internal project I'd even consider logging the dataFetch object below that for quicker inspection, though it might be much for something public facing.

**Comment by spasovski** [comment]
r+ from my side

File: src/components/containers/DashboardContainer.js (hunk 1 above)
Comment (pdehaan) [inline src/components/containers/DashboardContainer.js]: Do we have server logging for these? Like, do we know how common a dashboard-fetch-error is, or if it is a server issue?

Comment (openjck) [reply src/components/containers/DashboardContainer.js]: We don't, unfortunately. It's all static hosting.

Comment (openjck) [reply src/components/containers/DashboardContainer.js]: I suppose we could integrate with something like Sentry. Feel free to open an issue! :smiley:

Comment (openjck) [reply src/components/containers/DashboardContainer.js]: I didn't know the community took a dislike to these. Can you point me to some info about that?

**Comment by openjck** [comment]
Merged. Let me know about that `console.error` thing, @spasovski. I'm curious.
