### PR TITLE
Fix #121: Persist region between pageloads

### LINKED ISSUE #121: Persist Region between page loads
Per https://github.com/mozilla/ensemble-transposer/issues/57#issuecomment-382542019:

> _"Also, we should probably store the user's preferred category/locale/region in a cookie or localstorage so we can do a "best guess" on their desired category on future page loads (and preload the correct data if they go from _/user-activity_ to _/usage-behavior_) &mdash; but that's probably more of an **ensemble** issue, and not specific to the transposer."_

---

### Steps to reproduce:

1. Go to https://moz-ensemble.herokuapp.com/dashboard/user-activity
1. Set the region to "RU" (Russian).
1. Be amazed at the lovely charts.
1. Click the "Usage Behavior" link at the top-o-the-page.
1. Note the region switches from "RU" to the default "All".

### Expected results:

Persist my desired region between page loads.

### Actual results:

Region is reset to "All" on each new page load.

Not a huge deal, it's just one extra click, but if we do something like https://github.com/mozilla/ensemble-transposer/issues/57 where each region is it's own JSON file (which cuts an unnecessary 90% of the file), it'd potentially save us a network request.

### PR DESCRIPTION
**Pull request by openjck**

### CODE REVIEW

File: src/components/containers/DashboardContainer.js [hunk 1]
```diff
@@ -13,9 +13,12 @@ class DashboardContainer extends React.Component {
     }
 
     _onRegionChange = e => {
-        this.setState({
-            activeRegion: e.target.value,
-        });
+        const region = e.target.value;
```
Comment (spasovski) [inline src/components/containers/DashboardContainer.js]: I think this is safe since react should always pass the correct event and thus target but it's still weird to see no `if (!e.target) return;` 

Just musing...definitely cleaner this way anyway.

**Comment by spasovski** [comment]
r+. I didn't realize the `<Dashboard />` that triggers the region change is already in.

**Comment by openjck** [comment]
@spasovski Let's merge your Stylus change first, then I'll update this accordingly.

File: src/components/containers/DashboardContainer.js (hunk 1 above)
Comment (openjck) [reply src/components/containers/DashboardContainer.js]: Ah, that's a good idea. I'll add that.
